name: dart_language_server
version: 0.1.9+3
description: >-
  A shim on the analysis server following the language server protocol
homepage: https://github.com/natebosch/dart_language_server
authors:
  - Nate Bosch <nbosch1@gmail.com>

environment:
  sdk: ">=2.0.0-dev <2.0.0"

dependencies:
  analysis_server_lib: ^0.1.2+1
  args: ^1.0.0
  async: ^2.0.0
  json_rpc_2: ^2.0.3
  logging: ^0.11.3
  meta: ^1.1.0
  path: ^1.4.1
  pool: ^1.3.0
  stream_channel: ^1.5.0
  stream_transform: ^0.0.3

dev_dependencies:
  message_builder: ^0.1.3
  build_runner: ^0.7.0
  test: ^0.12.18

executables:
  dart_language_server: dart_language_server
